### ISSUE TITLE
[Sass API] Move Sass variables to polaris-tokens

### ISSUE THREAD

**Issue by alex-page** [Shopify/polaris-tokens#74]
# Context

For context on why we're doing this, see this issue: https://github.com/Shopify/polaris-react/issues/1982

**Why is this part of the Color system project?**

Good question. This work unlocks us (starting in version 5) to make changes to our Sass API without an impact on consumers. It will force consumers to stop relying on Polaris for Sass, and to use Tokens and their own internal Sass instead. Basically it paves the road for consumers to start using the Color system as CSS Custom properties, instead of using the `color` function (which will be removed) provided by Polaris Sass.

## Principles

- tokens should not be aliases to other tokens
- tokens should not do math for the consumer
- tokens should return pixel values and be transformed on the consumer
- tokens should convey **only** globally-useful data

⚠️ Names used in audit **do not** represent final names for tokens

**Comment by kaelig** [comment]
About tokens that are component-specific (button, caption, input…): the question you'll want to ask is "do I really want to have to update an external dependency to be able to update that value in the Polaris React library?".

Without going too deep in the nuance of what Theo/Design Tokens can bring, in a nutshell: if you'd rather have control over it easily in Polaris React, or if nobody ever asked to this value to be available outside of Polaris React, then it should probably live in Polaris React.

**Comment by alex-page** [comment]
I could be wrong. My assumption is that the tokens are sensible defaults that can be overriden in `polaris-react`. `polaris-tokens` creates the structure and naming conventions, the values can be changed if necessary.

**Comment by johanstromqvist** [comment]
**Regarding easing:**
1. I haven't seen `Excite`, `Overshoot` and `Anticipate` being applied anywhere. Would it be possible to remove them? We want to avoid bezier curves with values `<0` or `>1` for now as they don't convey the measured and restrained style we're going for. We might want to add either of these in the future, but in that case with specific intention and documentation.

2. I think the top three should either be called `in-out`, `in` and `out` to be more consistent, or `default`, `disappear` and `appear` to imply usage. I'm leaning to the latter. You should always be able to default to `default` and feel good about it.

3. In POS Next and any other animation work I've done, I've been using these following timing functions. They have good buy-in and are likely to stick around. [Reference.](https://docs.google.com/presentation/d/1n8ATjLYz0bcZBP2B-3ijK9GFXi6oQ-40cjQBM984jkY/edit#slide=id.g5126461b5c_0_418)
```
Default (ease-in-out): cubic-bezier(0.4, 0.22, 0.28, 1)
Appear (ease-out): cubic-bezier(0, 0, 0.13, 1)
Disappear (ease-in): cubic-bezier(0.5, 0.1, 1, 1)
```

**Comment by danrosenthal** [comment]
We use `base` in our other tokens to indicate `default`. I think I prefer `default`, but I prefer consistency in naming more. How do we feel about `base` instead of `default`?

**Comment by alex-page** [comment]
`base` feels like it grows or shrinks from this value. Which isn't always logically correct. I would prefer calling it what it is which is a default.

**Comment by danrosenthal** [comment]
> base feels like it grows or shrinks from this value.

That makes perfect sense!

**Comment by johanstromqvist** [comment]
Is it meaningful to call all base/default values either `base` or default`?

I think `default` is great as long as it's actually a default choice, i.e. when you don't know what token to choose, or if you don't have a specific reason to chose a specific one, you should be able to trust that default is a safe choice.

If that's not the case, then I don't think it should be called default.

A base font size from which all fonts scale doesn't make sense to call `default` imo. `Base` is a great name for that.

**Comment by danrosenthal** [comment]
# Final

Review here: #76 

## BorderWidths

```
props:
  - name: borderWidth-1
    value: 1px
  - name: borderWidth-2
    value: 2px
  - name: borderWidth-3
    value: 3px
global:
  type: number
  category: sizing
```

## Easings

```
props:
  - name: easing-default
    value: 'cubic-bezier(0.4, 0.22, 0.28, 1)'
  - name: easing-appear
    value: 'cubic-bezier(0, 0, 0.13, 1)'
  - name: easing-disappear
    value: 'cubic-bezier(0.5, 0.1, 1, 1)'
global:
  type: string
  category: easing
```

## Radii

```
props:
  - name: radius-3
    value: 3px
  - name: radius-6
    value: 6px
global:
  type: number
  category: radius
```

## Shadows

```
props:
  - name: shadow-faint
    value: '( 0 1px 0 0 rgba(22, 29, 37, 0.05), )'
  - name: shadow-default
    value: '( 0 0 0 1px rgba(63, 63, 68, 0.05), 0 1px 3px 0 rgba(63, 63, 68, 0.15), )'
  - name: shadow-deep
    value: '( 0 0 0 1px rgba(6, 44, 82, 0.1), 0 2px 16px rgba(33, 43, 54, 0.08), )'
  - name: shadow-layer
    value: '( 0 31px 41px 0 rgba(32, 42, 53, 0.2), 0 2px 16px 0 rgba(32, 42, 54, 0.08), )'
  - name: shadow-transparent
    value: '0 0 0 0 transparent'
global:
  type: string
  category: drop-shadow
```

## Sizes

```
props:
  - name: size-navigationWidth
    value: 240px
  - name: size-layoutWidth-oneHalf
    value: 450px
  - name: size-layoutWidth-oneThird
    value: 240px
  - name: size-layoutMinWidth-primary
    value: 480px
  - name: size-layoutMaxWidth-primary
    value: 662px
  - name: size-layoutMinWidth-secondary
    value: 240px
  - name: size-layoutMaxWidth-secondary
    value: 320px
  - name: size-pageIsPartiallyCondensed
    value: 450px
  - name: size-pageIsNotCondensed
    value: 680px
  - name: size-typographyIsCondensed
    value: 640px
  - name: size-navigationIsVisible
    value: 769px
global:
  type: number
  category: sizing
```
